# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventUserID', models.CharField(max_length=200)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
    ]
