# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventUserID', models.CharField(max_length=200)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('paymentName', models.CharField(max_length=200)),
                ('paymentNumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.AddField(
            model_name='eventuser',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
