# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventID',
            new_name='venueName',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='eventUserID',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venueID',
        ),
    ]
